"""Inject the trial EDA section into output/mentalriskes/trial_calibration_report.md.

Workflow:
  1. Reads the EDA Markdown produced by `eda_trial_data.py`
     (analysis/MentalRiskES_trial/outputs/eda_trial_data.md).
  2. Strips its top-level title and intro line so the inner sections (§1–4)
     become regular Markdown subsections.
  3. Renames §1–4 to §0.1–0.4 so the surrounding report's §1 (Experimental
     Setup) keeps its current numbering.
  4. Wraps the result in idempotent markers and either inserts a new
     `## 0. Trial Data EDA` section between the report's title and the
     existing `## 1. Experimental Setup`, OR replaces the previous
     marker-delimited block in place.

Run any time after eda_trial_data.py:
  python analysis/MentalRiskES_trial/update_trial_calibration_report.py
"""
from __future__ import annotations

import logging
import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
EDA_PATH = REPO_ROOT / "analysis/MentalRiskES_trial/outputs/eda_trial_data.md"
REPORT_PATH = REPO_ROOT / "output/mentalriskes/trial_calibration_report.md"

BEGIN_MARK = "<!-- BEGIN AUTO-GENERATED EDA -->"
END_MARK = "<!-- END AUTO-GENERATED EDA -->"


def _adapt_eda(md: str) -> str:
    """Strip top title + 'Auto-generated by' line; renumber sections to §0.x."""
    lines = md.splitlines()
    # Drop the H1 + (optional blank + intro paragraph + blank)
    while lines and not lines[0].startswith("##"):
        lines.pop(0)

    out: list[str] = []
    for ln in lines:
        m = re.match(r"^(##) (\d+)\. (.*)$", ln)
        if m:
            out.append(f"## 0.{m.group(2)} {m.group(3)}")
        else:
            out.append(ln)
    return "\n".join(out).rstrip() + "\n"


def main() -> None:
    logging.basicConfig(level="INFO", format="%(asctime)s [%(levelname)s] %(name)s: %(message)s")
    log = logging.getLogger("trial_report_updater")

    if not EDA_PATH.exists():
        raise FileNotFoundError(f"EDA file missing: {EDA_PATH}. Run eda_trial_data.py first.")

    eda_body = _adapt_eda(EDA_PATH.read_text(encoding="utf-8"))
    new_block = (
        "\n"
        f"{BEGIN_MARK}\n"
        "## 0. Trial Data EDA\n\n"
        f"*Auto-generated by [analysis/MentalRiskES_trial/eda_trial_data.py]"
        f"(../../analysis/MentalRiskES_trial/eda_trial_data.py); re-run that "
        f"script after any data changes.*\n\n"
        f"{eda_body}\n"
        f"{END_MARK}\n"
    )

    if not REPORT_PATH.exists():
        raise FileNotFoundError(f"Report missing: {REPORT_PATH}")
    report = REPORT_PATH.read_text(encoding="utf-8")

    if BEGIN_MARK in report and END_MARK in report:
        # Replace existing block in place
        pattern = re.compile(
            re.escape(BEGIN_MARK) + r".*?" + re.escape(END_MARK),
            re.DOTALL,
        )
        report = pattern.sub(new_block.strip(), report, count=1)
        log.info("Replaced existing EDA block in %s", REPORT_PATH)
    else:
        # Insert immediately AFTER the H1 title (first line starting with '# ')
        lines = report.splitlines(keepends=True)
        h1_idx = next((i for i, ln in enumerate(lines) if ln.startswith("# ")), None)
        if h1_idx is None:
            raise ValueError("No H1 title found in report")
        # find next blank line after H1 + the italics generated-from line
        insert_idx = h1_idx + 1
        while insert_idx < len(lines) and lines[insert_idx].strip() != "" and not lines[insert_idx].startswith("## "):
            insert_idx += 1
        # skip blank lines so we insert just before the next '## '
        while insert_idx < len(lines) and lines[insert_idx].strip() == "":
            insert_idx += 1
        # insert with surrounding blank lines
        prefix = "".join(lines[:insert_idx])
        suffix = "".join(lines[insert_idx:])
        report = prefix.rstrip() + "\n\n" + new_block.strip() + "\n\n" + suffix.lstrip()
        log.info("Inserted new EDA block into %s before existing §1", REPORT_PATH)

    REPORT_PATH.write_text(report, encoding="utf-8")
    log.info("Done: %s now contains the auto-generated EDA section", REPORT_PATH)


if __name__ == "__main__":
    main()
