"""Ablation study framework for MentalRiskES Task 1 calibration tiers.

Simulated-persona ablation:
  Validates calibration tiers on synthetic patient sessions generated by
  data_prep/simulator.py. Each session directory contains round_N.json
  files (same format as trial data) plus metadata.json with target_scores:
    {phq9_total: int, gad7_total: int, compact10_profile: str}

  derive_gold_from_metadata() converts these totals + profile into
  item-level gold vectors for RMSE/Pearson computation. The distribution
  is deterministic (seeded on session_id) and clinically motivated
  (see _PHQ9_WEIGHTS, _GAD7_WEIGHTS, _COMPACT10_PROFILE_SUBSCALES).

  run_ablation_on_simulated() iterates over all session dirs in a given
  root, runs each ablation config, aggregates metrics across sessions.


Implements the 6-configuration ablation (A0–A5) from:
  specs/MentalRiskES/mentalriskes2026_constraints_ablation_spec.md

Two modes:

1. Full LLM ablation — runs each config end-to-end on trial data (LLM required).
   A0: baseline (no anchors, no B, no C)
   A1: prompt anchors only                      [= official Run 2]
   A2: Level B rules only (no anchors)
   A3: prompt anchors + Level B                 [= official Run 1]
   A4: Level C agent only (no anchors, no B)
   A5: full stack (anchors + B + C)             [= official Run 0]

2. Post-hoc calibration ablation — takes an existing prediction log
   (JSONL output of a prior trial run) and applies Level B and/or C
   to the stored raw scores. No new LLM calls for assessment.
   Useful for quickly testing B/C contribution without re-running the LLM.
   Note: cannot retroactively apply Level A (prompt anchors change the input).
"""

from __future__ import annotations

import json
import logging
import math
import random
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from ..config import MentalRiskESConfig, RunConfig
from ..llm_client import LLMClient, create_llm_client
from ..metrics import evaluate_task1_full, format_task1_report
from .calibration import (
    ConstraintViolation,
    _should_invoke_level_c,
    apply_level_b_constraints,
    run_level_c_agent,
)
from .data import ConversationStore, load_trial_data
from .evaluation import TRIAL_GOLD

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Ablation configuration registry
# ---------------------------------------------------------------------------

def _make_run_config(
    name: str,
    description: str,
    prompt_anchors: bool,
    level_b: bool,
    level_c: bool,
    model: str = "llama3.3:70b",
    temporal_phq9: str = "T0",
    temporal_gad7: str = "T0",
    temporal_compact10: str = "T0",
    temporal_decay: str = "step",
) -> RunConfig:
    return RunConfig(
        name=name,
        description=description,
        model=model,
        few_shot=True,
        calibration="none",
        calibration_params={},
        prompt_anchors=prompt_anchors,
        level_b=level_b,
        level_c=level_c,
        temporal_phq9=temporal_phq9,
        temporal_gad7=temporal_gad7,
        temporal_compact10=temporal_compact10,
        temporal_decay=temporal_decay,
    )


# 6 configurations × (prompt_anchors, level_b, level_c)
ABLATION_CONFIGS: dict[str, RunConfig] = {
    "A0": _make_run_config(
        "A0", "Baseline — no anchors, no Level B, no Level C",
        prompt_anchors=False, level_b=False, level_c=False,
    ),
    "A1": _make_run_config(
        "A1", "Prompt anchors only [= official Run 2 — maximize Pearson]",
        prompt_anchors=True,  level_b=False, level_c=False,
    ),
    "A2": _make_run_config(
        "A2", "Level B rules only (no anchors, offline only)",
        prompt_anchors=False, level_b=True,  level_c=False,
    ),
    "A3": _make_run_config(
        "A3", "Anchors + Level B [= official Run 1 — safety hedge]",
        prompt_anchors=True,  level_b=True,  level_c=False,
    ),
    "A4": _make_run_config(
        "A4", "Level C agent only (no anchors, no B, offline only)",
        prompt_anchors=False, level_b=False, level_c=True,
    ),
    "A5": _make_run_config(
        "A5", "Full stack — anchors + Level B + Level C [= official Run 0]",
        prompt_anchors=True,  level_b=True,  level_c=True,
    ),
}

# ---------------------------------------------------------------------------
# Temporal ablation configs (spec section 8.2)
# Cross calibration level × temporal aggregation method
# ---------------------------------------------------------------------------

TEMPORAL_ABLATION_CONFIGS: dict[str, RunConfig] = {
    # Baseline: no calibration, no aggregation
    "A0-T0": ABLATION_CONFIGS["A0"],
    # Anchors only, last round
    "A1-T0": ABLATION_CONFIGS["A1"],
    # Anchors + early-weighted (isolates temporal effect)
    "A1-T2": _make_run_config(
        "A1-T2", "Anchors + early-weighted aggregation",
        prompt_anchors=True, level_b=False, level_c=False,
        temporal_phq9="T2", temporal_gad7="T2", temporal_compact10="T2",
    ),
    # + distress conditioning (spec A1+, same as A1 with temporal)
    "A1+-T2": _make_run_config(
        "A1+-T2", "Anchors + distress conditioning + early-weighted",
        prompt_anchors=True, level_b=False, level_c=False,
        temporal_phq9="T2", temporal_gad7="T2", temporal_compact10="T2",
    ),
    # + Level B constraints
    "A3-T2": _make_run_config(
        "A3-T2", "Anchors + Level B + early-weighted [= official Run 1]",
        prompt_anchors=True, level_b=True, level_c=False,
        temporal_phq9="T2", temporal_gad7="T2", temporal_compact10="T2",
    ),
    # Level B + stability-adaptive
    "A3-T3": _make_run_config(
        "A3-T3", "Anchors + Level B + stability-adaptive",
        prompt_anchors=True, level_b=True, level_c=False,
        temporal_phq9="T2", temporal_gad7="T2", temporal_compact10="T3",
    ),
    # Full stack with early-weighted
    "A5-T2": _make_run_config(
        "A5-T2", "Full stack + early-weighted",
        prompt_anchors=True, level_b=True, level_c=True,
        temporal_phq9="T2", temporal_gad7="T2", temporal_compact10="T2",
    ),
    # Full stack with stability-adaptive [= official Run 0]
    "A5-T3": _make_run_config(
        "A5-T3", "Full stack + stability-adaptive [= official Run 0]",
        prompt_anchors=True, level_b=True, level_c=True,
        temporal_phq9="T2", temporal_gad7="T2", temporal_compact10="T3",
    ),
}

# Official run mapping (updated for temporal)
OFFICIAL_RUN_MAP = {
    "run0_A5": "A5-T3",
    "run1_A3": "A3-T2",
    "run2_A1": "A1-T2",
}


# ---------------------------------------------------------------------------
# Per-round result structure
# ---------------------------------------------------------------------------

@dataclass
class RoundResult:
    """Assessment result for one session at one round."""
    session_id: str
    round_number: int
    phq9: list[int]
    gad7: list[int]
    compact10: list[int]
    level_b_violations: list[ConstraintViolation] = field(default_factory=list)
    level_c_corrections: list[dict] = field(default_factory=list)
    elapsed_s: float = 0.0


@dataclass
class AblationRunResult:
    """Full result for a single ablation configuration on trial data."""
    config_name: str
    description: str
    round_results: list[RoundResult] = field(default_factory=list)

    @property
    def final_result(self) -> RoundResult | None:
        """Last round result (for final evaluation against gold)."""
        return self.round_results[-1] if self.round_results else None

    def per_round_metrics(self, gold: dict[str, list[int]] | None = None) -> list[dict]:
        """RMSE per instrument per round (convergence trajectory)."""
        gold = gold or TRIAL_GOLD
        rows = []
        for rr in self.round_results:
            predicted = {"PHQ-9": rr.phq9, "GAD-7": rr.gad7, "CompACT-10": rr.compact10}
            metrics = evaluate_task1_full(predicted, gold)
            rows.append({
                "round": rr.round_number,
                "rmse_phq9": metrics["PHQ-9"]["rmse"],
                "rmse_gad7": metrics["GAD-7"]["rmse"],
                "rmse_compact10": metrics["CompACT-10"]["rmse"],
                "mean_rmse": metrics["_overall"]["mean_rmse"],
                "mean_pearson": metrics["_overall"]["mean_pearson"],
                "va_mean": sum(rr.compact10[i] for i in [1, 3, 6, 9]) / 4,
                "level_b_violations": len(rr.level_b_violations),
                "level_c_corrections": len(rr.level_c_corrections),
            })
        return rows

    def final_metrics(self, gold: dict[str, list[int]] | None = None) -> dict:
        """Full evaluation of the final-round prediction."""
        gold = gold or TRIAL_GOLD
        if not self.final_result:
            return {}
        predicted = {
            "PHQ-9": self.final_result.phq9,
            "GAD-7": self.final_result.gad7,
            "CompACT-10": self.final_result.compact10,
        }
        return evaluate_task1_full(predicted, gold)


# ---------------------------------------------------------------------------
# Full LLM ablation
# ---------------------------------------------------------------------------

def _uses_temporal(run_config: RunConfig) -> bool:
    """Check if any instrument uses temporal aggregation (not T0)."""
    return any(m != "T0" for m in [
        run_config.temporal_phq9,
        run_config.temporal_gad7,
        run_config.temporal_compact10,
    ])


def run_config_on_trial(
    run_config: RunConfig,
    trial_dir: str | Path,
    client: LLMClient,
    gold: dict[str, list[int]] | None = None,
) -> AblationRunResult:
    """Run a single ablation configuration on all trial rounds.

    Accumulates conversation history across rounds and produces one
    assessment per round. Returns AblationRunResult with per-round data.
    """
    from .assessors import assess_all_instruments
    from .calibration import calibrate_scores
    from .temporal import SessionPredictionHistory, apply_temporal_aggregation

    gold = gold or TRIAL_GOLD
    trial_data = load_trial_data(trial_dir)
    store = ConversationStore()

    # Prediction histories for temporal aggregation (keyed by session_id)
    histories: dict[str, SessionPredictionHistory] = {}
    use_temporal = _uses_temporal(run_config)

    result = AblationRunResult(
        config_name=run_config.name,
        description=run_config.description,
    )

    for round_n in sorted(trial_data.keys()):
        messages = trial_data[round_n]
        store.update_from_server_response(messages)

        for session_id, _ in messages.items():
            t0 = time.monotonic()
            context = store.get_context(session_id, max_turns=20)

            # Assessment (Level A injected here if prompt_anchors=True)
            assessments = assess_all_instruments(
                client,
                context,
                use_few_shot=run_config.few_shot,
                use_prompt_anchors=run_config.prompt_anchors,
            )

            phq9 = calibrate_scores(assessments["PHQ-9"].scores, "PHQ-9",
                                    run_config.calibration, run_config.calibration_params)
            gad7 = calibrate_scores(assessments["GAD-7"].scores, "GAD-7",
                                    run_config.calibration, run_config.calibration_params)
            compact10 = calibrate_scores(assessments["CompACT-10"].scores, "CompACT-10",
                                         run_config.calibration, run_config.calibration_params)

            # Level B
            violations: list[ConstraintViolation] = []
            if run_config.level_b:
                phq9, gad7, compact10, violations = apply_level_b_constraints(
                    phq9, gad7, compact10,
                )

            # Level C
            level_c_corrections: list[dict] = []
            if run_config.level_c and _should_invoke_level_c(
                violations, compact10, sum(phq9), sum(gad7),
            ):
                phq9, gad7, compact10, level_c_corrections = run_level_c_agent(
                    client, phq9, gad7, compact10, violations, assessments,
                )

            # Temporal aggregation
            if use_temporal:
                if session_id not in histories:
                    histories[session_id] = SessionPredictionHistory(session_id=session_id)
                history = histories[session_id]
                history.add_round(round_n, phq9, gad7, compact10)

                if history.n_rounds() >= 2:
                    agg = apply_temporal_aggregation(
                        history,
                        phq9_method=run_config.temporal_phq9,
                        gad7_method=run_config.temporal_gad7,
                        compact10_method=run_config.temporal_compact10,
                        decay=run_config.temporal_decay,
                        stability_threshold=run_config.temporal_stability_threshold,
                        w1_threshold_factor=run_config.temporal_w1_threshold,
                        discard_anomalous=run_config.temporal_discard_anomalous,
                    )
                    phq9 = agg["phq9"]
                    gad7 = agg["gad7"]
                    compact10 = agg["compact10"]

            elapsed = time.monotonic() - t0
            logger.info(
                "[%s] R%d %s: PHQ-9=%d GAD-7=%d CompACT-10=%d (%.1fs, %d B-violations)",
                run_config.name, round_n, session_id,
                sum(phq9), sum(gad7), sum(compact10), elapsed, len(violations),
            )

            result.round_results.append(RoundResult(
                session_id=session_id,
                round_number=round_n,
                phq9=phq9,
                gad7=gad7,
                compact10=compact10,
                level_b_violations=violations,
                level_c_corrections=level_c_corrections,
                elapsed_s=elapsed,
            ))

    return result


def run_ablation_study(
    configs: list[str] | None,
    trial_dir: str | Path,
    pipeline_cfg: MentalRiskESConfig,
    output_dir: str | Path = "runs/mentalriskes_ablation",
    gold: dict[str, list[int]] | None = None,
) -> dict[str, AblationRunResult]:
    """Run the full ablation study on trial data.

    Args:
        configs: list of config names to run (default: A0, A1, A3, A5).
          Full 6-config ablation: ["A0", "A1", "A2", "A3", "A4", "A5"].
          Quick 3-config (official runs only): ["A1", "A3", "A5"].
        trial_dir: path to trial data directory.
        pipeline_cfg: MentalRiskES pipeline config (for LLM settings).
        output_dir: directory to save per-config results.
        gold: gold scores (defaults to TRIAL_GOLD from evaluation.py).

    Returns:
        dict mapping config_name -> AblationRunResult.
    """
    gold = gold or TRIAL_GOLD
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)

    if configs is None:
        configs = ["A0", "A1", "A3", "A5"]  # default: baseline + official runs

    # Merge both config registries for lookup
    all_configs = {**ABLATION_CONFIGS, **TEMPORAL_ABLATION_CONFIGS}

    results: dict[str, AblationRunResult] = {}
    client = create_llm_client(pipeline_cfg.llm)

    for config_name in configs:
        if config_name not in all_configs:
            logger.warning("Unknown ablation config: %s (choices: %s)", config_name,
                           list(all_configs.keys()))
            continue

        run_config = all_configs[config_name]
        logger.info("=" * 60)
        logger.info("Running ablation %s: %s", config_name, run_config.description)
        logger.info("=" * 60)

        try:
            result = run_config_on_trial(run_config, trial_dir, client, gold)
            results[config_name] = result

            # Save per-config JSONL
            config_path = output_path / f"{config_name}_rounds.jsonl"
            with open(config_path, "w", encoding="utf-8") as f:
                for rr in result.round_results:
                    f.write(json.dumps({
                        "config": config_name,
                        "session_id": rr.session_id,
                        "round": rr.round_number,
                        "phq9": rr.phq9,
                        "gad7": rr.gad7,
                        "compact10": rr.compact10,
                        "level_b_violations": len(rr.level_b_violations),
                        "level_c_corrections": len(rr.level_c_corrections),
                        "elapsed_s": rr.elapsed_s,
                    }, ensure_ascii=False) + "\n")

            # Final metrics
            final_m = result.final_metrics(gold)
            logger.info(
                "%s final: PHQ-9 RMSE=%.3f, GAD-7 RMSE=%.3f, CompACT RMSE=%.3f, mean=%.3f",
                config_name,
                final_m.get("PHQ-9", {}).get("rmse", 0),
                final_m.get("GAD-7", {}).get("rmse", 0),
                final_m.get("CompACT-10", {}).get("rmse", 0),
                final_m.get("_overall", {}).get("mean_rmse", 0),
            )
        except Exception as e:
            logger.error("Ablation %s failed: %s", config_name, e, exc_info=True)

    # Save summary
    _save_ablation_summary(results, gold, output_path)

    return results


# ---------------------------------------------------------------------------
# Post-hoc calibration ablation (applies B/C to existing prediction logs)
# ---------------------------------------------------------------------------

def posthoc_calibration_ablation(
    raw_log_path: str | Path,
    gold: dict[str, list[int]] | None = None,
    apply_level_b: bool = True,
    apply_level_c: bool = False,
    client: LLMClient | None = None,
) -> dict:
    """Apply Level B and/or C post-hoc to existing prediction logs.

    Reads raw scores from a JSONL prediction log and applies the
    calibration tiers without re-running the LLM assessors.

    Limitation: cannot retroactively apply Level A (prompt anchors change
    the LLM input and thus the raw scores themselves).

    Args:
        raw_log_path: path to predictions_*.jsonl from a prior trial run.
        gold: gold scores (defaults to TRIAL_GOLD).
        apply_level_b: apply Level B constraints.
        apply_level_c: apply Level C LLM agent (requires client).
        client: LLMClient for Level C (required if apply_level_c=True).

    Returns:
        dict with per-round results and final metrics.
    """
    gold = gold or TRIAL_GOLD
    raw_path = Path(raw_log_path)

    rows = []
    with open(raw_path, "r", encoding="utf-8") as f:
        for line in f:
            rows.append(json.loads(line))

    processed = []
    for entry in rows:
        phq9 = entry["phq9"]
        gad7 = entry["gad7"]
        compact10 = entry["compact10"]
        round_n = entry.get("round", 0)
        session_id = entry.get("session_id", "")

        violations: list[ConstraintViolation] = []
        if apply_level_b:
            phq9, gad7, compact10, violations = apply_level_b_constraints(phq9, gad7, compact10)

        level_c_corrections: list[dict] = []
        if apply_level_c and client and _should_invoke_level_c(
            violations, compact10, sum(phq9), sum(gad7),
        ):
            phq9, gad7, compact10, level_c_corrections = run_level_c_agent(
                client, phq9, gad7, compact10, violations,
            )

        processed.append({
            "session_id": session_id,
            "round": round_n,
            "phq9": phq9,
            "gad7": gad7,
            "compact10": compact10,
            "level_b_violations": [v.rule for v in violations],
            "level_c_corrections": len(level_c_corrections),
        })

    # Find last prediction per session
    last_preds: dict[str, dict] = {}
    for entry in processed:
        last_preds[entry["session_id"]] = entry

    # Evaluate
    results_per_session = {}
    for sid, entry in last_preds.items():
        predicted = {
            "PHQ-9": entry["phq9"],
            "GAD-7": entry["gad7"],
            "CompACT-10": entry["compact10"],
        }
        results_per_session[sid] = evaluate_task1_full(predicted, gold)

    return {
        "source_log": str(raw_path),
        "apply_level_b": apply_level_b,
        "apply_level_c": apply_level_c,
        "n_rounds": len(rows),
        "per_round": processed,
        "final_metrics": results_per_session,
    }


# ---------------------------------------------------------------------------
# Simulated-persona ablation — gold derivation from metadata
# ---------------------------------------------------------------------------

# PHQ-9: 9 items (0-3), approximate clinical item weights
# Order: anhedonia, depressed_mood, sleep, fatigue, appetite,
#        worthlessness, concentration, psychomotor, SI
_PHQ9_WEIGHTS = [1.1, 1.1, 1.0, 1.0, 0.9, 1.0, 0.9, 0.8, 0.5]

# GAD-7: 7 items (0-3), approximate clinical item weights
# Order: anxious, uncontrollable_worry, excessive_worry, relaxing,
#        restless, irritable, afraid
_GAD7_WEIGHTS = [1.1, 1.0, 1.0, 0.9, 1.0, 0.9, 0.8]

# CompACT-10 profile → (OtE_mean, BA_mean, VA_mean) per item (0-4 scale)
# Subscale indices: OtE=[2,4,7], BA=[0,5,8], VA=[1,3,6,9]
# Higher = more psychological flexibility
_COMPACT10_PROFILE_SUBSCALES: dict[str, tuple[float, float, float]] = {
    "low_flexibility":      (1.0, 1.5, 2.0),  # avoidant, disconnected from values
    "moderate_flexibility": (2.3, 2.5, 2.5),  # moderate across board
    "mixed_flexibility":    (1.5, 2.0, 2.8),  # values-aware but experientially avoidant
    "high_flexibility":     (3.2, 3.0, 3.2),  # fully flexible
}
_OTE_IDX = [2, 4, 7]
_BA_IDX = [0, 5, 8]
_VA_IDX = [1, 3, 6, 9]


def _distribute_total(
    total: int,
    weights: list[float],
    max_val: int,
) -> list[int]:
    """Distribute `total` across len(weights) items proportionally, capped at max_val.

    Deterministic: uses fraction-based rounding adjustment (no RNG).
    """
    n = len(weights)
    w_sum = sum(weights)
    raw = [total * w / w_sum for w in weights]
    scores = [min(max_val, max(0, round(r))) for r in raw]

    diff = total - sum(scores)
    if diff != 0:
        # Sort by fractional part to decide where to add/subtract
        fracs = sorted(range(n), key=lambda i: raw[i] - int(raw[i]), reverse=(diff > 0))
        for i in fracs:
            if diff == 0:
                break
            if diff > 0 and scores[i] < max_val:
                scores[i] += 1
                diff -= 1
            elif diff < 0 and scores[i] > 0:
                scores[i] -= 1
                diff += 1

    return scores


def derive_gold_from_metadata(metadata: dict) -> dict[str, list[int]]:
    """Derive item-level gold scores from simulation metadata.

    Args:
        metadata: contents of metadata.json, containing 'target_scores' with
            phq9_total (int), gad7_total (int), compact10_profile (str).

    Returns:
        dict with "PHQ-9" (9 ints, 0-3), "GAD-7" (7 ints, 0-3),
        "CompACT-10" (10 ints, 0-4).

    Note:
        The item distribution is clinically motivated but approximate —
        only the totals (PHQ-9 and GAD-7) and subscale profile (CompACT-10)
        are reliable ground truth from the simulator. RMSE numbers should
        be interpreted relative across configs, not as absolute accuracy.
    """
    target = metadata["target_scores"]
    phq9_total: int = target["phq9_total"]
    gad7_total: int = target["gad7_total"]
    compact10_profile: str = target.get("compact10_profile", "moderate_flexibility")

    # PHQ-9
    phq9 = _distribute_total(phq9_total, _PHQ9_WEIGHTS, max_val=3)

    # GAD-7
    gad7 = _distribute_total(gad7_total, _GAD7_WEIGHTS, max_val=3)

    # CompACT-10 — derive subscale totals from profile, then distribute across items
    ote_mean, ba_mean, va_mean = _COMPACT10_PROFILE_SUBSCALES.get(
        compact10_profile, (2.0, 2.0, 2.0),
    )
    ote_total = max(0, min(len(_OTE_IDX) * 4, round(ote_mean * len(_OTE_IDX))))
    ba_total = max(0, min(len(_BA_IDX) * 4, round(ba_mean * len(_BA_IDX))))
    va_total = max(0, min(len(_VA_IDX) * 4, round(va_mean * len(_VA_IDX))))

    ote_scores = _distribute_total(ote_total, [1.0] * len(_OTE_IDX), max_val=4)
    ba_scores = _distribute_total(ba_total, [1.0] * len(_BA_IDX), max_val=4)
    va_scores = _distribute_total(va_total, [1.0] * len(_VA_IDX), max_val=4)

    compact10 = [0] * 10
    for k, idx in enumerate(_OTE_IDX):
        compact10[idx] = ote_scores[k]
    for k, idx in enumerate(_BA_IDX):
        compact10[idx] = ba_scores[k]
    for k, idx in enumerate(_VA_IDX):
        compact10[idx] = va_scores[k]

    return {"PHQ-9": phq9, "GAD-7": gad7, "CompACT-10": compact10}


# ---------------------------------------------------------------------------
# Simulated-persona ablation — multi-session runner
# ---------------------------------------------------------------------------

def run_ablation_on_simulated(
    simulated_dir: str | Path,
    configs: list[str] | None,
    pipeline_cfg: MentalRiskESConfig,
    output_dir: str | Path = "runs/mentalriskes_simulated_ablation",
) -> dict[str, dict[str, AblationRunResult]]:
    """Run ablation on all simulated persona sessions.

    Args:
        simulated_dir: root directory containing one sub-dir per simulated
            session (each has round_N.json files + metadata.json).
        configs: ablation config names to run (default: A0, A1, A3, A5).
        pipeline_cfg: MentalRiskES pipeline config (for LLM settings).
        output_dir: directory to save per-session and aggregated results.

    Returns:
        dict mapping session_id -> {config_name -> AblationRunResult}.
        The derived gold for each session is embedded in AblationRunResult
        via per_round_metrics(gold) / final_metrics(gold).
    """
    simulated_dir = Path(simulated_dir)
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)

    if configs is None:
        configs = ["A0", "A1", "A3", "A5"]

    # Discover session directories
    session_dirs = sorted(
        d for d in simulated_dir.iterdir()
        if d.is_dir() and (d / "metadata.json").exists()
    )
    if not session_dirs:
        logger.warning("No simulated sessions found in %s", simulated_dir)
        return {}

    logger.info("Found %d simulated sessions in %s", len(session_dirs), simulated_dir)
    client = create_llm_client(pipeline_cfg.llm)

    # session_id -> config_name -> AblationRunResult
    all_results: dict[str, dict[str, AblationRunResult]] = {}
    # session_id -> derived gold (stored for reporting)
    all_gold: dict[str, dict[str, list[int]]] = {}

    for session_dir in session_dirs:
        meta_path = session_dir / "metadata.json"
        with open(meta_path, "r", encoding="utf-8") as f:
            metadata = json.load(f)

        session_id = metadata["session_id"]
        gold = derive_gold_from_metadata(metadata)
        all_gold[session_id] = gold

        profile_id = metadata.get("profile", {}).get("id", session_id)
        t = metadata["target_scores"]
        logger.info("=" * 60)
        logger.info("Session: %s (profile: %s)", session_id, profile_id)
        logger.info(
            "  Target PHQ-9=%d GAD-7=%d CompACT=%s | Derived gold: PHQ-9=%d GAD-7=%d CompACT=%d",
            t["phq9_total"], t["gad7_total"], t["compact10_profile"],
            sum(gold["PHQ-9"]), sum(gold["GAD-7"]), sum(gold["CompACT-10"]),
        )

        session_results: dict[str, AblationRunResult] = {}

        for config_name in configs:
            if config_name not in ABLATION_CONFIGS:
                logger.warning("Unknown ablation config: %s", config_name)
                continue

            run_config = ABLATION_CONFIGS[config_name]
            logger.info("  Config %s: %s", config_name, run_config.description)

            try:
                result = run_config_on_trial(run_config, session_dir, client, gold)
                session_results[config_name] = result

                m = result.final_metrics(gold)
                logger.info(
                    "  %s done: PHQ-9 RMSE=%.3f GAD-7 RMSE=%.3f CompACT RMSE=%.3f mean=%.3f",
                    config_name,
                    m.get("PHQ-9", {}).get("rmse", 0),
                    m.get("GAD-7", {}).get("rmse", 0),
                    m.get("CompACT-10", {}).get("rmse", 0),
                    m.get("_overall", {}).get("mean_rmse", 0),
                )
            except Exception as e:
                logger.error(
                    "Session %s config %s failed: %s", session_id, config_name, e,
                    exc_info=True,
                )

        all_results[session_id] = session_results

        # Save per-session summary
        sess_out = output_path / session_id
        sess_out.mkdir(exist_ok=True)
        _save_simulated_session_summary(session_id, session_results, gold, metadata, sess_out)

    # Save aggregated report
    report = format_simulated_ablation_report(all_results, all_gold, configs)
    report_path = output_path / "simulated_ablation_report.txt"
    report_path.write_text(report, encoding="utf-8")
    logger.info("Simulated ablation report saved to %s", report_path)
    print(report)

    return all_results


def _save_simulated_session_summary(
    session_id: str,
    session_results: dict[str, AblationRunResult],
    gold: dict[str, list[int]],
    metadata: dict,
    output_dir: Path,
) -> None:
    """Save per-session ablation summary JSON."""
    summary: dict[str, Any] = {
        "session_id": session_id,
        "profile": metadata.get("profile", {}),
        "target_scores": metadata.get("target_scores", {}),
        "derived_gold": {inst: scores for inst, scores in gold.items()},
        "configs": {},
    }

    for config_name, result in session_results.items():
        m = result.final_metrics(gold)
        summary["configs"][config_name] = {
            "description": result.description,
            "final_metrics": {
                inst: {k: round(v, 4) if isinstance(v, float) else v
                       for k, v in inst_m.items()
                       if isinstance(v, (int, float, bool, str))}
                for inst, inst_m in m.items()
                if isinstance(inst_m, dict)
            },
            "trajectory": result.per_round_metrics(gold),
        }

    path = output_dir / "ablation_summary.json"
    path.write_text(json.dumps(summary, indent=2, ensure_ascii=False))


# ---------------------------------------------------------------------------
# Simulated ablation report
# ---------------------------------------------------------------------------

def format_simulated_ablation_report(
    all_results: dict[str, dict[str, AblationRunResult]],
    all_gold: dict[str, dict[str, list[int]]],
    configs: list[str] | None = None,
) -> str:
    """Format multi-session simulated ablation report with mean ± std.

    Args:
        all_results: session_id -> {config_name -> AblationRunResult}.
        all_gold: session_id -> derived gold dict (for final_metrics calls).
        configs: ordered list of config names to include.
    """
    configs = configs or ["A0", "A1", "A3", "A5"]
    n_sessions = len(all_results)

    def _mean(vals: list[float]) -> float:
        valid = [v for v in vals if not math.isnan(v)]
        return sum(valid) / len(valid) if valid else float("nan")

    def _std(vals: list[float]) -> float:
        valid = [v for v in vals if not math.isnan(v)]
        if len(valid) < 2:
            return 0.0
        m = sum(valid) / len(valid)
        return math.sqrt(sum((v - m) ** 2 for v in valid) / (len(valid) - 1))

    # Collect metrics per config across sessions
    config_metrics: dict[str, dict[str, list[float]]] = {
        c: {"mean_rmse": [], "mean_pearson": [], "phq9_rmse": [], "gad7_rmse": [], "compact10_rmse": []}
        for c in configs
    }

    for session_id, session_results in all_results.items():
        gold = all_gold.get(session_id, {})
        for config_name in configs:
            if config_name not in session_results:
                continue
            m = session_results[config_name].final_metrics(gold) if gold else {}
            cm = config_metrics[config_name]
            cm["mean_rmse"].append(m.get("_overall", {}).get("mean_rmse", float("nan")))
            cm["mean_pearson"].append(m.get("_overall", {}).get("mean_pearson", float("nan")))
            cm["phq9_rmse"].append(m.get("PHQ-9", {}).get("rmse", float("nan")))
            cm["gad7_rmse"].append(m.get("GAD-7", {}).get("rmse", float("nan")))
            cm["compact10_rmse"].append(m.get("CompACT-10", {}).get("rmse", float("nan")))

    lines = [
        "=" * 85,
        "MentalRiskES Task 1 — Simulated Persona Ablation",
        f"Sessions: {n_sessions} | Configs: {', '.join(configs)}",
        "Note: item-level gold derived from phq9_total/gad7_total/compact10_profile",
        "      RMSE values are relative across configs, not absolute accuracy.",
        "=" * 85,
        "",
        "Aggregated Metrics across sessions (mean ± std):",
        f"{'Config':<8} {'Anchors':>8} {'LvlB':>6} {'LvlC':>6} "
        f"{'PHQ9-RMSE':>15} {'GAD7-RMSE':>15} {'CACT-RMSE':>15} {'MeanRMSE':>15}",
        "-" * 85,
    ]

    for config_name in configs:
        if config_name not in ABLATION_CONFIGS:
            continue
        run_cfg = ABLATION_CONFIGS[config_name]
        cm = config_metrics[config_name]

        anc = "Y" if run_cfg.prompt_anchors else "N"
        lvlb = "Y" if run_cfg.level_b else "N"
        lvlc = "Y" if run_cfg.level_c else "N"

        p9m, p9s = _mean(cm["phq9_rmse"]), _std(cm["phq9_rmse"])
        g7m, g7s = _mean(cm["gad7_rmse"]), _std(cm["gad7_rmse"])
        cam, cas = _mean(cm["compact10_rmse"]), _std(cm["compact10_rmse"])
        mrm, mrs = _mean(cm["mean_rmse"]), _std(cm["mean_rmse"])

        lines.append(
            f"{config_name:<8} {anc:>8} {lvlb:>6} {lvlc:>6} "
            f"{p9m:>7.3f}±{p9s:<6.3f} "
            f"{g7m:>7.3f}±{g7s:<6.3f} "
            f"{cam:>7.3f}±{cas:<6.3f} "
            f"{mrm:>7.3f}±{mrs:<6.3f}"
        )

    # Delta rows
    lines += ["", "Deltas (positive = improvement, lower RMSE):"]
    for label, c1, c2 in [
        ("A5 vs A3 (agent effect) ", "A5", "A3"),
        ("A3 vs A1 (rules effect) ", "A3", "A1"),
        ("A5 vs A0 (full stack)   ", "A5", "A0"),
    ]:
        if c1 in config_metrics and c2 in config_metrics:
            deltas = []
            for sid in all_results:
                gold = all_gold.get(sid, {})
                sr = all_results[sid]
                if c1 in sr and c2 in sr and gold:
                    m1 = sr[c1].final_metrics(gold).get("_overall", {}).get("mean_rmse", float("nan"))
                    m2 = sr[c2].final_metrics(gold).get("_overall", {}).get("mean_rmse", float("nan"))
                    if not (math.isnan(m1) or math.isnan(m2)):
                        deltas.append(m2 - m1)  # positive = c1 better
            if deltas:
                n_better = sum(1 for d in deltas if d > 0)
                lines.append(
                    f"  {label}: mean RMSE delta={_mean(deltas):+.3f}±{_std(deltas):.3f} "
                    f"({c1} better in {n_better}/{len(deltas)} sessions)"
                )

    # Per-session breakdown
    lines += [
        "",
        "Per-Session Breakdown (final-round mean RMSE):",
        f"{'Session':<32}" + "".join(f" {c:>10}" for c in configs),
        "-" * (32 + 11 * len(configs)),
    ]

    for session_id in sorted(all_results):
        gold = all_gold.get(session_id, {})
        row = f"{session_id:<32}"
        for config_name in configs:
            sr = all_results[session_id]
            if config_name in sr and gold:
                val = sr[config_name].final_metrics(gold).get("_overall", {}).get("mean_rmse", float("nan"))
                row += f" {val:>10.3f}"
            else:
                row += f" {'N/A':>10}"
        lines.append(row)

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Reporting
# ---------------------------------------------------------------------------

def format_ablation_comparison(
    results: dict[str, AblationRunResult],
    gold: dict[str, list[int]] | None = None,
) -> str:
    """Format ablation results as a comparison table (Tables 1–4 from spec)."""
    gold = gold or TRIAL_GOLD
    gold_va_mean = sum(gold["CompACT-10"][i] for i in [1, 3, 6, 9]) / 4

    lines = [
        "=" * 75,
        "MentalRiskES Task 1 — Calibration Ablation Results",
        "Spec: mentalriskes2026_constraints_ablation_spec.md",
        "=" * 75,
    ]

    # Table 1: Final-round metrics per config
    lines += [
        "",
        "Table 1: Final-Round Metrics per Configuration",
        f"{'Config':<8} {'Anchors':>8} {'LvlB':>6} {'LvlC':>6} "
        f"{'PHQ9-RMSE':>10} {'GAD7-RMSE':>10} {'CACT-RMSE':>10} "
        f"{'MeanRMSE':>10} {'MeanPear':>10}",
        "-" * 75,
    ]

    for config_name in ["A0", "A1", "A2", "A3", "A4", "A5"]:
        if config_name not in results:
            continue
        run_cfg = ABLATION_CONFIGS[config_name]
        m = results[config_name].final_metrics(gold)
        phq9_r = m.get("PHQ-9", {}).get("rmse", float("nan"))
        gad7_r = m.get("GAD-7", {}).get("rmse", float("nan"))
        cact_r = m.get("CompACT-10", {}).get("rmse", float("nan"))
        mean_r = m.get("_overall", {}).get("mean_rmse", float("nan"))
        mean_p = m.get("_overall", {}).get("mean_pearson", float("nan"))

        anc = "Y" if run_cfg.prompt_anchors else "N"
        lvlb = "Y" if run_cfg.level_b else "N"
        lvlc = "Y" if run_cfg.level_c else "N"

        lines.append(
            f"{config_name:<8} {anc:>8} {lvlb:>6} {lvlc:>6} "
            f"{phq9_r:>10.3f} {gad7_r:>10.3f} {cact_r:>10.3f} "
            f"{mean_r:>10.3f} {mean_p:>10.3f}"
        )

    # Delta rows (official run comparisons)
    lines += ["", "Deltas (positive = Run N better than Run M):"]
    for label, c1, c2 in [
        ("Run0-Run1 (agent effect)", "A5", "A3"),
        ("Run1-Run2 (rules effect)", "A3", "A1"),
        ("Run0-Run2 (full stack)  ", "A5", "A1"),
    ]:
        if c1 in results and c2 in results:
            m1 = results[c1].final_metrics(gold)
            m2 = results[c2].final_metrics(gold)
            delta_mean = (m2.get("_overall", {}).get("mean_rmse", 0)
                         - m1.get("_overall", {}).get("mean_rmse", 0))
            lines.append(f"  {label}: mean RMSE delta={delta_mean:+.3f} (lower=better)")

    # Table 2: CompACT-10 subscale analysis
    lines += [
        "",
        "Table 2: CompACT-10 Subscale Analysis (VA bias is the primary calibration target)",
        f"{'Config':<8} {'OtE-RMSE':>10} {'BA-RMSE':>10} {'VA-RMSE':>10} "
        f"{'VA-bias':>10} {'B-viols':>8} {'C-corrs':>8}",
        "-" * 75,
    ]

    for config_name in ["A0", "A1", "A2", "A3", "A4", "A5"]:
        if config_name not in results:
            continue
        run_result = results[config_name]
        m = run_result.final_metrics(gold)
        cact = m.get("CompACT-10", {})
        ote_r = cact.get("subscale_openness_rmse", float("nan"))
        ba_r = cact.get("subscale_awareness_rmse", float("nan"))
        va_r = cact.get("subscale_valued_action_rmse", float("nan"))

        # VA bias: mean predicted VA - gold VA
        if run_result.final_result:
            pred_va = sum(run_result.final_result.compact10[i] for i in [1, 3, 6, 9]) / 4
            va_bias = pred_va - gold_va_mean
        else:
            va_bias = float("nan")

        total_b = sum(len(rr.level_b_violations) for rr in run_result.round_results)
        total_c = sum(len(rr.level_c_corrections) for rr in run_result.round_results)

        lines.append(
            f"{config_name:<8} {ote_r:>10.3f} {ba_r:>10.3f} {va_r:>10.3f} "
            f"{va_bias:>+10.2f} {total_b:>8} {total_c:>8}"
        )

    # Table 3: Per-round convergence summary (first round within ±3 of gold CompACT total)
    gold_compact_total = sum(gold["CompACT-10"])
    lines += [
        "",
        "Table 3: Convergence — first round where CompACT-10 total within ±3 of gold "
        f"({gold_compact_total})",
        f"{'Config':<8} {'Converge-Round':>15}",
        "-" * 25,
    ]

    for config_name in ["A0", "A1", "A2", "A3", "A4", "A5"]:
        if config_name not in results:
            continue
        converge_round = None
        for rr in results[config_name].round_results:
            if abs(sum(rr.compact10) - gold_compact_total) <= 3:
                converge_round = rr.round_number
                break
        lines.append(f"{config_name:<8} {str(converge_round) if converge_round else 'never':>15}")

    return "\n".join(lines)


def format_posthoc_report(result: dict, gold: dict[str, list[int]] | None = None) -> str:
    """Format post-hoc calibration ablation results."""
    gold = gold or TRIAL_GOLD
    lines = [
        "=" * 65,
        "MentalRiskES Task 1 — Post-Hoc Calibration Ablation",
        f"Source: {result['source_log']}",
        f"Level B: {result['apply_level_b']} | Level C: {result['apply_level_c']}",
        f"Rounds processed: {result['n_rounds']}",
        "=" * 65,
    ]

    for sid, metrics in result["final_metrics"].items():
        lines.append(f"\nSession: {sid}")
        from ..metrics import format_task1_report
        lines.append(format_task1_report(metrics))

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Summary saving
# ---------------------------------------------------------------------------

def _save_ablation_summary(
    results: dict[str, AblationRunResult],
    gold: dict[str, list[int]],
    output_path: Path,
) -> None:
    """Save ablation summary JSON and comparison report."""
    summary = {}
    for config_name, run_result in results.items():
        m = run_result.final_metrics(gold)
        summary[config_name] = {
            "description": run_result.description,
            "config": {
                "prompt_anchors": ABLATION_CONFIGS[config_name].prompt_anchors,
                "level_b": ABLATION_CONFIGS[config_name].level_b,
                "level_c": ABLATION_CONFIGS[config_name].level_c,
            },
            "final_metrics": {
                inst: {k: round(v, 4) if isinstance(v, float) else v
                       for k, v in inst_metrics.items()
                       if isinstance(v, (int, float, bool, str))}
                for inst, inst_metrics in m.items()
                if isinstance(inst_metrics, dict)
            },
            "trajectory": run_result.per_round_metrics(gold),
        }

    summary_path = output_path / "ablation_summary.json"
    summary_path.write_text(json.dumps(summary, indent=2, ensure_ascii=False))
    logger.info("Ablation summary saved to %s", summary_path)

    report = format_ablation_comparison(results, gold)
    report_path = output_path / "ablation_report.txt"
    report_path.write_text(report, encoding="utf-8")
    logger.info("Ablation report saved to %s", report_path)
    print(report)
